-- +goose Up
-- Imports of other apps' backups (Mihon, Tachiyomi, Suwayomi, Aidoku): the
-- upload and its options, and one row per manga with how it was mapped.
CREATE TABLE imports (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    format     TEXT      NOT NULL,
    file_name  TEXT      NOT NULL,
    status     TEXT      NOT NULL,
    progress   TEXT      NOT NULL DEFAULT '',
    options    JSONB     NOT NULL DEFAULT '{}',
    info       JSONB     NOT NULL DEFAULT '{}',
    error      TEXT      NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE import_entries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id  BIGINT    NOT NULL REFERENCES imports (id) ON DELETE CASCADE,
    position   INTEGER   NOT NULL,
    title      TEXT      NOT NULL,
    state      TEXT      NOT NULL,
    selected   BOOLEAN   NOT NULL DEFAULT TRUE,
    data       JSONB     NOT NULL DEFAULT '{}',
    source     JSONB,
    metadata   JSONB,
    extension  JSONB,
    series_id  BIGINT  REFERENCES series (id) ON DELETE SET NULL,
    message    TEXT      NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX import_entries_import ON import_entries (import_id, position);

-- Scanlators excluded for one series (literal names, e.g. from Mihon).
ALTER TABLE series ADD COLUMN blocked_scanlators JSONB NOT NULL DEFAULT '[]';
-- Where a read state came from: '' = a library server, 'backup' = an
-- imported backup (kept until a server reports the chapter).
ALTER TABLE chapter_read_states ADD COLUMN origin TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE chapter_read_states DROP COLUMN origin;
ALTER TABLE series DROP COLUMN blocked_scanlators;
DROP INDEX import_entries_import;
DROP TABLE import_entries;
DROP TABLE imports;
