-- +goose Up
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT      NOT NULL UNIQUE,
    password_hash TEXT      NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE settings (
    key        TEXT PRIMARY KEY,
    value      TEXT      NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE tags (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL UNIQUE
);

CREATE TABLE root_folders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path       TEXT      NOT NULL UNIQUE,
    language   TEXT      NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE profiles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT      NOT NULL UNIQUE,
    is_default BOOLEAN   NOT NULL DEFAULT FALSE,
    config     JSONB      NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE provider_definitions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind           TEXT      NOT NULL,
    implementation TEXT      NOT NULL,
    name           TEXT      NOT NULL,
    enabled        BOOLEAN   NOT NULL DEFAULT TRUE,
    priority       INTEGER   NOT NULL DEFAULT 25,
    tags           JSONB      NOT NULL DEFAULT '[]',
    events         JSONB      NOT NULL DEFAULT '[]',
    settings       JSONB      NOT NULL DEFAULT '{}',
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL
);
CREATE INDEX provider_definitions_kind ON provider_definitions (kind);

CREATE TABLE series (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                 TEXT      NOT NULL,
    sort_title            TEXT      NOT NULL,
    status                TEXT      NOT NULL DEFAULT 'unknown',
    monitored             BOOLEAN   NOT NULL DEFAULT TRUE,
    monitor_new           TEXT      NOT NULL DEFAULT 'all',
    root_folder_id        BIGINT   NOT NULL REFERENCES root_folders (id),
    path                  TEXT      NOT NULL,
    profile_id            BIGINT   NOT NULL REFERENCES profiles (id),
    language              TEXT      NOT NULL DEFAULT '',
    reading_direction     TEXT      NOT NULL DEFAULT 'rtl',
    tags                  JSONB      NOT NULL DEFAULT '[]',
    metadata              JSONB      NOT NULL DEFAULT '{}',
    add_options           JSONB      NOT NULL DEFAULT '{}',
    added_at              TIMESTAMPTZ NOT NULL,
    updated_at            TIMESTAMPTZ NOT NULL,
    last_metadata_refresh TIMESTAMPTZ
);
CREATE UNIQUE INDEX series_root_path ON series (root_folder_id, path);

CREATE TABLE series_sources (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id              BIGINT   NOT NULL REFERENCES series (id) ON DELETE CASCADE,
    module_id              BIGINT   NOT NULL,
    source_id              TEXT      NOT NULL,
    source_name            TEXT      NOT NULL DEFAULT '',
    lang                   TEXT      NOT NULL DEFAULT '',
    manga_url              TEXT      NOT NULL,
    title                  TEXT      NOT NULL DEFAULT '',
    web_url                TEXT      NOT NULL DEFAULT '',
    engine_ref             TEXT      NOT NULL DEFAULT '',
    priority               INTEGER   NOT NULL DEFAULT 0,
    enabled                BOOLEAN   NOT NULL DEFAULT TRUE,
    check_interval_minutes INTEGER   NOT NULL DEFAULT 0,
    last_checked_at        TIMESTAMPTZ,
    last_success_at        TIMESTAMPTZ,
    next_check_at          TIMESTAMPTZ NOT NULL,
    consecutive_failures   INTEGER   NOT NULL DEFAULT 0,
    backoff_until          TIMESTAMPTZ,
    last_error             TEXT      NOT NULL DEFAULT '',
    created_at             TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX series_sources_identity ON series_sources (series_id, source_id, manga_url);
CREATE INDEX series_sources_next_check ON series_sources (next_check_at);

CREATE TABLE chapters (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id     BIGINT   NOT NULL REFERENCES series (id) ON DELETE CASCADE,
    number_key    TEXT      NOT NULL,
    number_sort   DOUBLE PRECISION      NOT NULL,
    volume        TEXT      NOT NULL DEFAULT '',
    title         TEXT      NOT NULL DEFAULT '',
    monitored     BOOLEAN   NOT NULL DEFAULT TRUE,
    state         TEXT      NOT NULL DEFAULT 'missing',
    file_id       BIGINT,
    cleaned_at    TIMESTAMPTZ,
    release_date  TIMESTAMPTZ,
    first_seen_at TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX chapters_series_number ON chapters (series_id, number_key);
CREATE INDEX chapters_state ON chapters (state);

CREATE TABLE chapter_releases (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id        BIGINT   NOT NULL REFERENCES series (id) ON DELETE CASCADE,
    chapter_id       BIGINT REFERENCES chapters (id) ON DELETE SET NULL,
    series_source_id BIGINT   NOT NULL REFERENCES series_sources (id) ON DELETE CASCADE,
    chapter_url      TEXT      NOT NULL,
    web_url          TEXT      NOT NULL DEFAULT '',
    engine_ref       TEXT      NOT NULL DEFAULT '',
    name             TEXT      NOT NULL DEFAULT '',
    scanlator        TEXT      NOT NULL DEFAULT '',
    raw_number       DOUBLE PRECISION      NOT NULL DEFAULT -1,
    upload_date      TIMESTAMPTZ,
    removed          BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX chapter_releases_identity ON chapter_releases (series_source_id, chapter_url);
CREATE INDEX chapter_releases_chapter ON chapter_releases (chapter_id);

CREATE TABLE chapter_files (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id    BIGINT   NOT NULL REFERENCES chapters (id) ON DELETE CASCADE,
    series_id     BIGINT   NOT NULL REFERENCES series (id) ON DELETE CASCADE,
    relative_path TEXT      NOT NULL,
    size          BIGINT   NOT NULL DEFAULT 0,
    page_count    INTEGER   NOT NULL DEFAULT 0,
    avg_width     INTEGER   NOT NULL DEFAULT 0,
    format        TEXT      NOT NULL DEFAULT '',
    release_id    BIGINT,
    scanlator     TEXT      NOT NULL DEFAULT '',
    source_name   TEXT      NOT NULL DEFAULT '',
    sha256        TEXT      NOT NULL DEFAULT '',
    upscaled      BOOLEAN   NOT NULL DEFAULT FALSE,
    upscale_model TEXT      NOT NULL DEFAULT '',
    size_before   BIGINT   NOT NULL DEFAULT 0,
    imported_at   TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX chapter_files_chapter ON chapter_files (chapter_id);

CREATE TABLE download_jobs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        TEXT      NOT NULL DEFAULT 'download',
    series_id   BIGINT   NOT NULL REFERENCES series (id) ON DELETE CASCADE,
    chapter_id  BIGINT   NOT NULL REFERENCES chapters (id) ON DELETE CASCADE,
    release_id  BIGINT,
    status      TEXT      NOT NULL,
    progress    INTEGER   NOT NULL DEFAULT 0,
    pages_done  INTEGER   NOT NULL DEFAULT 0,
    pages_total INTEGER   NOT NULL DEFAULT 0,
    attempt     INTEGER   NOT NULL DEFAULT 0,
    is_upgrade  BOOLEAN   NOT NULL DEFAULT FALSE,
    error       TEXT      NOT NULL DEFAULT '',
    not_before  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    started_at  TIMESTAMPTZ
);
CREATE INDEX download_jobs_status ON download_jobs (status);
-- at most one active job per chapter (enqueue races resolve to the existing job)
CREATE UNIQUE INDEX download_jobs_active_chapter ON download_jobs (chapter_id)
    WHERE status IN ('queued', 'downloading', 'processing', 'importing');

CREATE TABLE history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id    BIGINT   NOT NULL,
    chapter_id   BIGINT,
    event_type   TEXT      NOT NULL,
    source_title TEXT      NOT NULL DEFAULT '',
    data         JSONB      NOT NULL DEFAULT '{}',
    created_at   TIMESTAMPTZ NOT NULL
);
CREATE INDEX history_series ON history (series_id);
CREATE INDEX history_created ON history (created_at);

CREATE TABLE blocklist (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id        BIGINT   NOT NULL REFERENCES series (id) ON DELETE CASCADE,
    chapter_id       BIGINT,
    series_source_id BIGINT   NOT NULL,
    chapter_url      TEXT      NOT NULL,
    scanlator        TEXT      NOT NULL DEFAULT '',
    reason           TEXT      NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX blocklist_identity ON blocklist (series_source_id, chapter_url);

CREATE TABLE commands (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT      NOT NULL,
    body        JSONB      NOT NULL DEFAULT '{}',
    status      TEXT      NOT NULL,
    "trigger"   TEXT      NOT NULL DEFAULT 'manual',
    message     TEXT      NOT NULL DEFAULT '',
    queued_at   TIMESTAMPTZ NOT NULL,
    started_at  TIMESTAMPTZ,
    ended_at    TIMESTAMPTZ,
    duration_ms BIGINT   NOT NULL DEFAULT 0,
    error       TEXT      NOT NULL DEFAULT ''
);
CREATE INDEX commands_status ON commands (status);

CREATE TABLE scheduled_tasks (
    name             TEXT PRIMARY KEY,
    interval_minutes INTEGER NOT NULL,
    last_execution   TIMESTAMPTZ,
    last_start       TIMESTAMPTZ
);

CREATE TABLE readers (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT      NOT NULL UNIQUE,
    count_for_cleanup BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL
);

CREATE TABLE reader_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id     BIGINT   NOT NULL REFERENCES readers (id) ON DELETE CASCADE,
    module_id     BIGINT   NOT NULL,
    credentials   JSONB      NOT NULL DEFAULT '{}',
    external_user TEXT      NOT NULL DEFAULT '',
    last_sync_at  TIMESTAMPTZ,
    last_error    TEXT      NOT NULL DEFAULT '',
    created_at    TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX reader_accounts_identity ON reader_accounts (reader_id, module_id);

CREATE TABLE chapter_read_states (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id  BIGINT   NOT NULL REFERENCES readers (id) ON DELETE CASCADE,
    chapter_id BIGINT   NOT NULL REFERENCES chapters (id) ON DELETE CASCADE,
    series_id  BIGINT   NOT NULL,
    completed  BOOLEAN   NOT NULL DEFAULT FALSE,
    page       INTEGER   NOT NULL DEFAULT 0,
    read_at    TIMESTAMPTZ,
    synced_at  TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX chapter_read_states_identity ON chapter_read_states (reader_id, chapter_id);
CREATE INDEX chapter_read_states_series ON chapter_read_states (series_id);

-- +goose Down
DROP TABLE chapter_read_states;
DROP TABLE reader_accounts;
DROP TABLE readers;
DROP TABLE scheduled_tasks;
DROP TABLE commands;
DROP TABLE blocklist;
DROP TABLE history;
DROP TABLE download_jobs;
DROP TABLE chapter_files;
DROP TABLE chapter_releases;
DROP TABLE chapters;
DROP TABLE series_sources;
DROP TABLE series;
DROP TABLE provider_definitions;
DROP TABLE profiles;
DROP TABLE root_folders;
DROP TABLE tags;
DROP TABLE settings;
DROP TABLE users;
