-- +goose Up
-- A work is the canonical title; series remain language-specific editions
-- with their own files, sources, profile, progress and queue state.
CREATE TABLE works (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      TEXT        NOT NULL,
    sort_title TEXT        NOT NULL,
    metadata   JSONB       NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
ALTER TABLE series ADD COLUMN work_id BIGINT REFERENCES works (id);
INSERT INTO works (id, title, sort_title, metadata, created_at, updated_at)
SELECT id, title, sort_title, metadata, added_at, updated_at FROM series;
UPDATE series SET work_id = id WHERE work_id IS NULL;
CREATE INDEX series_work ON series (work_id);
SELECT setval(pg_get_serial_sequence('works', 'id'), COALESCE((SELECT MAX(id) FROM works), 1), true);

-- +goose Down
DROP INDEX series_work;
ALTER TABLE series DROP COLUMN work_id;
DROP TABLE works;
