-- +goose Up
-- Workers are machines that do work for this server: they hold a key of
-- their own, dial in, and ask for tasks. The counters are their lifetime
-- totals (worker_tasks keeps the detail).
CREATE TABLE workers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL UNIQUE,
    key_hash      TEXT        NOT NULL UNIQUE,
    prefix        TEXT        NOT NULL,
    roles         JSONB       NOT NULL DEFAULT '[]',
    enabled       BOOLEAN     NOT NULL DEFAULT TRUE,
    version       TEXT        NOT NULL DEFAULT '',
    platform      TEXT        NOT NULL DEFAULT '',
    info          JSONB       NOT NULL DEFAULT '{}',
    last_ip       TEXT        NOT NULL DEFAULT '',
    created_by    BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    last_seen_at  TIMESTAMPTZ,
    tasks_done    BIGINT      NOT NULL DEFAULT 0,
    tasks_failed  BIGINT      NOT NULL DEFAULT 0,
    pages_done    BIGINT      NOT NULL DEFAULT 0,
    bytes_in      BIGINT      NOT NULL DEFAULT 0,
    bytes_out     BIGINT      NOT NULL DEFAULT 0,
    busy_seconds  DOUBLE PRECISION NOT NULL DEFAULT 0
);

-- +goose Down
DROP TABLE workers;
