-- +goose Up
-- One piece of work handed to a worker. A download job becomes one download
-- task, and later upscale and encode tasks, so this is a table of its own
-- rather than columns on download_jobs — and the finished rows are what the
-- worker statistics are counted from.
CREATE TABLE worker_tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id       BIGINT      NOT NULL REFERENCES download_jobs (id) ON DELETE CASCADE,
    worker_id    BIGINT      REFERENCES workers (id) ON DELETE SET NULL,
    kind         TEXT        NOT NULL,
    seq          INTEGER     NOT NULL DEFAULT 0,
    state        TEXT        NOT NULL,
    spec         JSONB       NOT NULL DEFAULT '{}',
    not_before   TIMESTAMPTZ NOT NULL,
    lease_until  TIMESTAMPTZ,
    heartbeat_at TIMESTAMPTZ,
    cancel       BOOLEAN     NOT NULL DEFAULT FALSE,
    attempt      INTEGER     NOT NULL DEFAULT 0,
    pages_total  INTEGER     NOT NULL DEFAULT 0,
    pages_done   INTEGER     NOT NULL DEFAULT 0,
    bytes_in     BIGINT      NOT NULL DEFAULT 0,
    bytes_out    BIGINT      NOT NULL DEFAULT 0,
    error        TEXT        NOT NULL DEFAULT '',
    created_at   TIMESTAMPTZ NOT NULL,
    started_at   TIMESTAMPTZ,
    finished_at  TIMESTAMPTZ
);
CREATE INDEX worker_tasks_waiting ON worker_tasks (state, kind, not_before);
CREATE INDEX worker_tasks_leases ON worker_tasks (state, lease_until);
CREATE INDEX worker_tasks_job ON worker_tasks (job_id);
CREATE INDEX worker_tasks_worker ON worker_tasks (worker_id, state);

-- +goose Down
DROP TABLE worker_tasks;
