package envcfg

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"text/tabwriter"

	"github.com/Asion001/mangarr/internal/modules"
	"github.com/Asion001/mangarr/internal/settings"
	"github.com/Asion001/mangarr/internal/upscaler"
	"github.com/Asion001/mangarr/internal/worker"
)

// WriteText prints the variables as a table, marking the ones that are set.
func WriteText(w io.Writer, env map[string]string) {
	tw := tabwriter.NewWriter(w, 2, 4, 2, ' ', 0)
	fmt.Fprintln(tw, "VARIABLE\tSET\tDEFAULT\tDESCRIPTION")
	for _, v := range All(env) {
		set := ""
		if v.Set {
			set = "yes"
		}
		fmt.Fprintf(tw, "%s\t%s\t%s\t%s\n", v.Name, set, v.Default, v.Description)
	}
	_ = tw.Flush()
	if u := Unknown(env); len(u) > 0 {
		fmt.Fprintf(w, "\nUnknown variables (ignored): %s\n", strings.Join(u, ", "))
	}
}

func mdEscape(s string) string {
	return strings.NewReplacer("|", `\|`, "<", "&lt;", ">", "&gt;").Replace(s)
}

// WriteMarkdown writes docs/configuration.md.
func WriteMarkdown(w io.Writer) {
	p := func(format string, a ...any) { fmt.Fprintf(w, format, a...) }
	p("# Configuration with environment variables\n\n")
	p("<!-- generated by `mangarr env --markdown`; do not edit -->\n\n")
	p("Everything can be configured in the UI. Values set with environment variables are **locked**: the UI shows them with a lock icon and can't change them. ")
	p("Removing a variable makes the field editable again and restores the value that was saved before.\n\n")
	p("Lists are comma-separated (`a,b,c`) or JSON; key/value settings use `key=value,key2=value2`.\n\n")

	p("## Process\n\n| Variable | Default | Description |\n|---|---|---|\n")
	for _, v := range CoreVars(nil) {
		p("| `%s` | `%s` | %s |\n", v.Name, mdEscape(v.Default), mdEscape(v.Description))
	}

	p("\n## Workers (`MANGARR_MODE=worker`)\n\n")
	p("A worker holds a key of its own and asks the server for work, so it needs no port and no inbound access.\n\n")
	p("| Variable | Default | Description |\n|---|---|---|\n")
	for _, v := range worker.Vars {
		p("| `%s` | `%s` | %s |\n", v[0], mdEscape(v[2]), mdEscape(worker.Help[v[0]]))
	}

	p("\n## The upscaling engine\n\n")
	p("Read wherever the engine runs: in the server, or on a worker with the upscale role.\n\n")
	p("| Variable | Old name | Default | Description |\n|---|---|---|---|\n")
	engineDesc := map[string]string{
		"MANGARR_UPSCALER_TOOLS_DIR": "Folder with the ncnn upscalers.",
		"MANGARR_UPSCALER_GPU":       "Vulkan device indices: auto selects one default device, or use a comma-separated list such as 0,1 to run batches in parallel across those devices.", "MANGARR_UPSCALER_THREADS": "ncnn load:proc:save threads.",
		"MANGARR_UPSCALER_TILE":    "Tile size (0 = auto, from the GPU's memory; lower on small GPUs).",
		"MANGARR_UPSCALER_TIMEOUT": "Maximum time per batch.", "MANGARR_UPSCALER_TMP_DIR": "Scratch folder.", "MANGARR_UPSCALER_CWEBP": "Path to cwebp.",
	}
	for _, v := range upscaler.EngineVars {
		p("| `%s` | %s | `%s` | %s |\n", v[0], mdEscape(v[1]), mdEscape(v[2]), mdEscape(engineDesc[v[0]]))
	}

	p("\n## Settings\n\n")
	for _, d := range settings.Docs {
		p("### %s\n\n| Variable | Type | Default | Description |\n|---|---|---|---|\n", d.Name)
		for _, f := range fieldsOf(d.Default(), d.EnvPrefix) {
			def := mask(formatDefault(f.def), f.secret)
			p("| `%s` | %s | `%s` | %s |\n", f.env, typeName(f.typ), mdEscape(def), mdEscape(f.desc))
		}
		p("\n")
	}

	p("## Modules\n\n")
	p("Module instances are declared with `MANGARR_MODULE_<NAME>_IMPL=<kind>/<implementation>`; `<NAME>` is any identifier you choose ")
	p("(it keeps the instance's identity, so don't rename it). Then set fields with `MANGARR_MODULE_<NAME>_<FIELD>` and optionally:\n\n")
	p("| Suffix | Meaning |\n|---|---|\n")
	p("| `_NAME` | Display name (default: derived from `<NAME>`) |\n")
	p("| `_ENABLED` | `true`/`false` (default true for new instances) |\n")
	p("| `_ORDER` | Priority; lower runs first |\n")
	p("| `_SERIES_TAGS` | Tag labels limiting which series the instance handles |\n")
	p("| `_EVENTS` | Notification events (notify modules) |\n\n")
	p("An instance created in the UI with the same implementation and name is adopted instead of duplicated. ")
	p("Env-defined instances can't be deleted in the UI; when the variables are removed the instance stays and becomes editable.\n\n")
	p("Example:\n\n```env\nMANGARR_MODULE_SUWAYOMI_IMPL=source/suwayomi\nMANGARR_MODULE_SUWAYOMI_URL=http://suwayomi:4567\n")
	p("MANGARR_MODULE_SUWAYOMI_FLARE_SOLVERR_ENABLED=true\nMANGARR_MODULE_KOMGA_IMPL=library/komga\nMANGARR_MODULE_KOMGA_URL=http://komga:25600\n")
	p("MANGARR_MODULE_KOMGA_API_KEY=...\n```\n\n")

	kinds := []modules.Kind{modules.KindSource, modules.KindMetadata, modules.KindLibrary, modules.KindNotify, modules.KindUpscale}
	for _, k := range kinds {
		for _, impl := range modules.Implementations(k) {
			p("### `%s/%s` — %s\n\n| Suffix | Type | Description |\n|---|---|---|\n", k, impl.Name, impl.DisplayName)
			fields := moduleFields(impl)
			helps := map[string]string{}
			for _, f := range modules.FieldsOf(impl.Settings()) {
				helps[f.Name] = strings.TrimSpace(f.Label + ". " + f.Help)
			}
			var names []string
			for s := range fields {
				names = append(names, s)
			}
			sort.Strings(names)
			for _, s := range names {
				f := fields[s]
				p("| `_%s` | %s | %s |\n", s, typeName(f.typ), mdEscape(strings.TrimSuffix(helps[f.name], ".")))
			}
			p("\n")
		}
	}
}
